
-- Create the educations table
CREATE TABLE public.educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    content TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Function to update updated_at column
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at on row update
CREATE TRIGGER on_education_update
BEFORE UPDATE ON public.educations
FOR EACH ROW
EXECUTE PROCEDURE public.handle_updated_at();

-- Enable RLS
ALTER TABLE public.educations ENABLE ROW LEVEL SECURITY;

-- Policies for educations table
-- 1. Allow public read access
CREATE POLICY "Allow public read access to educations"
ON public.educations
FOR SELECT
USING (true);

-- 2. Allow admin to insert
CREATE POLICY "Allow admin to insert educations"
ON public.educations
FOR INSERT
WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- 3. Allow admin to update
CREATE POLICY "Allow admin to update educations"
ON public.educations
FOR UPDATE
USING (auth.jwt() ->> 'role' = 'admin')
WITH CHECK (auth.jwt() ->> 'role' = 'admin');

-- 4. Allow admin to delete
CREATE POLICY "Allow admin to delete educations"
ON public.educations
FOR DELETE
USING (auth.jwt() ->> 'role' = 'admin');

-- Create storage bucket for education images
INSERT INTO storage.buckets (id, name, public)
VALUES ('education_images', 'education_images', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for education_images storage
-- 1. Allow public read access
CREATE POLICY "Allow public read access to education_images"
ON storage.objects
FOR SELECT
USING (bucket_id = 'education_images');

-- 2. Allow admin to insert
CREATE POLICY "Allow admin to insert into education_images"
ON storage.objects
FOR INSERT
WITH CHECK (bucket_id = 'education_images' AND auth.jwt() ->> 'role' = 'admin');

-- 3. Allow admin to update
CREATE POLICY "Allow admin to update education_images"
ON storage.objects
FOR UPDATE
USING (bucket_id = 'education_images' AND auth.jwt() ->> 'role' = 'admin')
WITH CHECK (bucket_id = 'education_images' AND auth.jwt() ->> 'role' = 'admin');

-- 4. Allow admin to delete
CREATE POLICY "Allow admin to delete from education_images"
ON storage.objects
FOR DELETE
USING (bucket_id = 'education_images' AND auth.jwt() ->> 'role' = 'admin');
