-- =================================================================
-- Update Foreign Key and RPC to use pass_questions
-- =================================================================
--
-- Problem:
-- The `screening_answers` table has a foreign key to `gad7_questions`,
-- and the `get_screening_details` function also joins with `gad7_questions`.
-- These need to be updated to point to the new `pass_questions` table.
--
-- Solution:
-- 1. Drop the old foreign key constraint from `screening_answers`.
-- 2. Add a new foreign key constraint that references `pass_questions`.
-- 3. Re-create the `get_screening_details` function to join with `pass_questions`.

-- 1. Drop the old foreign key and add the new one.
-- NOTE: The constraint name 'screening_answers_question_id_fkey' is the default
-- name generated by PostgreSQL. If this fails, the name might be different.
ALTER TABLE public.screening_answers
DROP CONSTRAINT screening_answers_question_id_fkey,
ADD CONSTRAINT screening_answers_question_id_fkey
  FOREIGN KEY (question_id)
  REFERENCES public.pass_questions(id)
  ON DELETE CASCADE; -- Optional: cascade delete if a question is ever deleted.

-- 2. Update the get_screening_details function to use the new table.
-- We use CREATE OR REPLACE to safely update it.
DROP FUNCTION IF EXISTS public.get_screening_details(uuid) CASCADE;
CREATE FUNCTION public.get_screening_details(p_screening_id uuid)
RETURNS TABLE (
    -- Screening Info
    screening_id uuid,
    completed_at timestamptz,
    total_score integer,
    anxiety_level public.anxiety_level,
    status public.screening_status,
    notes text,
    -- Profile Info
    full_name text,
    email text,
    -- Question and Answer Info
    question_text text,
    answer_score integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    SELECT
        s.id as screening_id,
        s.completed_at,
        s.total_score,
        s.anxiety_level,
        s.status,
        s.notes,
        p.full_name,
        p.email,
        pq.question_text, -- Changed from gq.question_text
        sa.score as answer_score
    FROM
        public.screenings s
    JOIN
        public.profiles p ON s.user_id = p.id
    JOIN
        public.screening_answers sa ON sa.screening_id = s.id
    LEFT JOIN
        public.pass_questions pq ON sa.question_id = pq.id -- Changed from gad7_questions
    WHERE
        s.id = p_screening_id
    ORDER BY
        pq.question_order ASC NULLS LAST;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_screening_details(uuid) TO authenticated;
