// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiowxbqfgfsvtxsuowxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpb3d4YnFmZ2ZzdnR4c3Vvd3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODU4NTEsImV4cCI6MjA3MjI2MTg1MX0.geyQ5GT4ikMzfafB4rMNqtb3xJ-AmoA9tf2M9lqugC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});